# SERVER PORT (Render s? c?p c?ng ng?u nhiên qua bi?n PORT)
server.port=${PORT:8080}

# DATABASE - K?t n?i Supabase (Dùng c?ng 6543 ?? ?n ??nh nh?t)
spring.datasource.url=jdbc:postgresql://db.jkeigjeakgxjrwqcxgqq.supabase.co:6543/postgres?sslmode=require
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / HIBERNATE
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# DISCORD CONFIG
discord.bot.token=${BOT_TOKEN}
discord.bot.prefix=!